### PR TITLE
chore: add up-to-date citation file for version 2023

### LINKED ISSUE #28: Add CITATION.cff in place of Citation
- [x] Can we do a Citation.cff file for this lesson? How do people cite carpentries lessons?
- [x] Fill out the citation file.
- Update citation for 2024  Replaced by #42

### PR DESCRIPTION
**Pull request by hollandjg**
- Add a new CITATION.cff file.
- Delete old CITATION file.

We use the standard in the template from Carpentries – flagging this as a dataset. https://github.com/carpentries/workbench-template-md/blob/main/CITATION.cff

- resolves #28

### CODE REVIEW

**Review by henryiii — APPROVED** [review]
:heart:

**Comment by henryiii** [comment]
(You don't need to worry about reviews unless there's something specific you'd like me to look at)

**Comment by hollandjg** [comment]
> (You don't need to worry about reviews unless there's something specific you'd like me to look at)

Hey Henry, thanks for the quick review! I requested your review explicitly on this one because I wanted to check that I have your name and your ORCID correct – I think I copied them correctly, but I wanted to check. On any others where I don't ask directly for a review, I still appreciate your input but I understand that you might not be able to look at PRs all the time.

**Comment by hollandjg** [comment]
(At the same time, if you _do_ have time and are able to review my PRs, I'm extremely appreciative.)

**Comment by henryiii** [comment]
Looks right, I’m just comparing it with my GitHub profile.

**Pull request merged**
